### ISSUE TITLE
Defining `head` property in Nuxt

### ISSUE THREAD

**Issue by arpadgabor** [antfu/vue2-script-setup-transform#11]
As you probably know, in `@nuxtjs/composition-api` you must add an empty `head: {}` to use the [`useMeta`](https://composition-api.nuxtjs.org/packages/useMeta) composition function.

Maybe it's going over my head but, is there any way at the moment to do this with `<script setup>`?

**Comment by antfu** [comment]
`<script setup>` allow the co-existence with the normal `<script>`, meaning you can use this as a current workaround:

```html
<script setup>
import { useMeta } from  '@nuxtjs/composition-api'

useMeta({ ... })
</script>

<script>
export default {
  head: {}
}
</script>
```

/cc @@danielroe do you see if there is a way to by pass this limitation or we have to do that in compile time?

**Comment by mirabledictu** [comment]
How about  the Nuxt `middleware` property?

**Comment by mirabledictu** [comment]
BTW this shows up with current workaround

![Screen Shot 2021-08-22 at 10 55 14 PM](https://user-images.githubusercontent.com/86201195/130359737-014d85ee-b9d2-44af-a239-9425a3cb98a7.png)

**Comment by arpadgabor** [comment]
Just tried your suggestion @antfu, but `useMeta` seems to be ignored.

```js
// nuxt.config.js
head: {
  title: 'Hello there'
}
```

```vue
// pages/index.vue

<script setup lang="ts">
import { useMeta } from '@nuxtjs/composition-api'

useMeta({
  title: 'General Kenobi', // ignored
})
</script>

<script lang="ts">
export default {
  head: {}, // the title only changes if I put it here.
}
</script>
```

Here is a [codesandbox](https://codesandbox.io/s/heuristic-panini-s0kmk).

Also, trying to write a component with `defineComponent` breaks build:

```
 ERROR  Cannot overwrite a zero-length range – use appendLeft or prependRight instead                                                                                                                           18:33:47

  at MagicString.overwrite (node_modules/magic-string/dist/magic-string.cjs.js:657:11)
  at transform (node_modules/vue2-script-setup-transform/dist/chunk-YQNABFGI.js:461:5)
  at Object.transform (node_modules/vue2-script-setup-transform/dist/chunk-CIXBJ6SU.js:16:41)
  at Object.transform (node_modules/vue2-script-setup-transform/node_modules/unplugin/dist/webpack/loaders/transform.cjs:11:28)
  at LOADER_EXECUTION (node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
  at runSyncOrAsync (node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
  at iterateNormalLoaders (node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
  at Array.<anonymous> (node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
  at Storage.finished (node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
  at node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
  at node_modules/graceful-fs/graceful-fs.js:123:16
  at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:73:3)
```

**Comment by arpadgabor** [comment]
@mirabledictu if you are using TypeScript, don't forget to write the `lang="ts"` to both script tags.

**Comment by mirabledictu** [comment]
> Just tried your suggestion @antfu, but `useMeta` seems to be ignored.
> 
> ```js
> // nuxt.config.js
> head: {
>   title: 'Hello there'
> }
> ```
> 
> ```
> // pages/index.vue
> 
> <script setup lang="ts">
> import { useMeta } from '@nuxtjs/composition-api'
> 
> useMeta({
>   title: 'General Kenobi', // ignored
> })
> </script>
> 
> <script lang="ts">
> export default {
>   head: {}, // the title only changes if I put it here.
> }
> </script>
> ```
> 
> Here is a [codesandbox](https://codesandbox.io/s/heuristic-panini-s0kmk).
> 
> ~Also, trying to write a component with `defineComponent` breaks build:~ Fixed in latest release
> 
> ```
>  ERROR  Cannot overwrite a zero-length range – use appendLeft or prependRight instead                                                                                                                           18:33:47
> 
>   at MagicString.overwrite (node_modules/magic-string/dist/magic-string.cjs.js:657:11)
>   at transform (node_modules/vue2-script-setup-transform/dist/chunk-YQNABFGI.js:461:5)
>   at Object.transform (node_modules/vue2-script-setup-transform/dist/chunk-CIXBJ6SU.js:16:41)
>   at Object.transform (node_modules/vue2-script-setup-transform/node_modules/unplugin/dist/webpack/loaders/transform.cjs:11:28)
>   at LOADER_EXECUTION (node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
>   at runSyncOrAsync (node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
>   at iterateNormalLoaders (node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
>   at Array.<anonymous> (node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
>   at Storage.finished (node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
>   at node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
>   at node_modules/graceful-fs/graceful-fs.js:123:16
>   at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:73:3)
> ```

hi, is the workaround really working?

**Comment by yinfoyuan** [comment]
<script lang="ts" setup>
import { useMeta, defineComponent } from '@nuxtjs/composition-api'

const { title } = useMeta()

title.value = 'a'

</script>

<script lang="ts">
export default defineComponent({
  head: {}
})
</script>

**Comment by yinfoyuan** [comment]
```
<script lang="ts" setup>
import { useContext, useAsync, ref, useMeta, defineComponent } from '@nuxtjs/composition-api'

const { $axios } = useContext()

const fontUrl = ref<string>('')
const title = ref('a')

useAsync(async () => {
  title.value = 'b'
  fontUrl.value = await $axios.$get('/xxx')
})

useMeta(() => ({
  title: title.value
}))

</script>
```

```
<script lang="ts">
export default defineComponent({
  head: {}
})
</script>
```
```
import { defineComponent as defineComponent$1 } from '@nuxtjs/composition-api'

declare global {
  const defineComponent: typeof defineComponent$1
}

```
I worked it out for now, but...
```
 ERROR  document is not defined                                                                                                                                                          13:49:30  

  at Object.newNotificationInstance [as newInstance] (server.js:10161:13)
  at getMessageInstance (server.js:9575:31)
  at server.js:9611:5
  at new Promise (<anonymous>)
  at Object.notice [as open] (server.js:9604:22)
  at Object.api.<computed> [as error] (server.js:9703:16)
  at errorCallback (server.js:12016:71)
  at server.js:381:56
  at runMicrotasks (<anonymous>)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
