### ISSUE TITLE
Webpack dev server down when emit an error

### ISSUE THREAD

**Issue by sxzz** [antfu/vue2-script-setup-transform#16]
When there is a problem in code, the webpack dev server will directly report an error and exit.

```
node_modules/.pnpm/@babel+parser@7.15.3/node_modules/@babel/parser/lib/index.js:798
    const err = new SyntaxError(message);
                ^

SyntaxError: Unexpected token (1:5)
    at Parser._raise (node_modules/.pnpm/@babel+parser@7.15.3/node_modules/@babel/parser/lib/index.js:798:17)
    at Parser.raiseWithData (node_modules/.pnpm/@babel+parser@7.15.3/node_modules/@babel/parser/lib/index.js:791:17)
    at Parser.raise (node_modules/.pnpm/@babel+parser@7.15.3/node_modules/@babel/parser/lib/index.js:752:17)
    at Parser.unexpected (node_modules/.pnpm/@babel+parser@7.15.3/node_modules/@babel/parser/lib/index.js:3257:16)
    at Parser.parseIdentifierName (node_modules/.pnpm/@babel+parser@7.15.3/node_modules/@babel/parser/lib/index.js:12362:18)
    at Parser.parseIdentifier (node_modules/.pnpm/@babel+parser@7.15.3/node_modules/@babel/parser/lib/index.js:12340:23)
    at Parser.parseMember (node_modules/.pnpm/@babel+parser@7.15.3/node_modules/@babel/parser/lib/index.js:11140:103)
    at Parser.parseSubscript (node_modules/.pnpm/@babel+parser@7.15.3/node_modules/@babel/parser/lib/index.js:11127:19)
    at Parser.parseSubscripts (node_modules/.pnpm/@babel+parser@7.15.3/node_modules/@babel/parser/lib/index.js:11098:19)
    at Parser.parseExprSubscripts (node_modules/.pnpm/@babel+parser@7.15.3/node_modules/@babel/parser/lib/index.js:11087:17)
    at Parser.parseUpdate (node_modules/.pnpm/@babel+parser@7.15.3/node_modules/@babel/parser/lib/index.js:11061:21)
    at Parser.parseMaybeUnary (node_modules/.pnpm/@babel+parser@7.15.3/node_modules/@babel/parser/lib/index.js:11039:23)
    at Parser.parseExprOps (node_modules/.pnpm/@babel+parser@7.15.3/node_modules/@babel/parser/lib/index.js:10882:23)
    at Parser.parseMaybeConditional (node_modules/.pnpm/@babel+parser@7.15.3/node_modules/@babel/parser/lib/index.js:10856:23)
    at Parser.parseMaybeAssign (node_modules/.pnpm/@babel+parser@7.15.3/node_modules/@babel/parser/lib/index.js:10814:21)
    at node_modules/.pnpm/@babel+parser@7.15.3/node_modules/@babel/parser/lib/index.js:10776:39 {
  loc: Position { line: 1, column: 5 },
  pos: 5,
  code: 'BABEL_PARSER_SYNTAX_ERROR',
  reasonCode: 'UnexpectedToken'
}
 ERROR  Command failed with exit code 1.
```

**Comment by antfu** [comment]
is there are a way to solve this?

**Comment by sxzz** [comment]
`unplugin` should expose `this` context, and use `ctx.emitError`

 https://webpack.docschina.org/api/loaders/#thisemiterror

P.S. `unplugin` is not open source yet

**Comment by xiaoxiangmoe** [comment]
你的版本是最新的吗？能给个复现吗？

**Comment by guohuihot** [comment]
> 你的版本是最新的吗？能给个复现吗？

晚上我弄个最小复现

**Comment by guohuihot** [comment]
> 你的版本是最新的吗？能给个复现吗？

https://gitee.com/i-ahuing_demos/vue_unplugins_error
```src\App.vue```
![image](https://github.com/antfu/unplugin-vue2-script-setup/assets/3119995/a0c92491-fc3a-4a09-9902-93899d75a498)
