### ISSUE TITLE
Webpack plugin doesn't work on Webpack 5 (vue-cli)

### ISSUE THREAD

**Issue by sxzz** [antfu/vue2-script-setup-transform#5]
```javascript
// vue.config.js
const ScriptSetup = require("vue2-script-setup-transform/webpack-plugin").default;

/**
 * @type {import('@vue/cli-service').ProjectOptions}
 */
module.exports = {
  configureWebpack: {
    plugins: [ScriptSetup()],
  },
};
```

Error: 
```
****/node_modules/unplugin/dist/webpack/loaders/transform.cjs:7
  const plugin = (_a = this._compiler) == null ? void 0 : _a.$unpluginContext[unpluginName];
                                                                             ^

TypeError: Cannot read property 'vue2-script-setup-transform' of undefined
    at Object.transform (****/node_modules/unplugin/dist/webpack/loaders/transform.cjs:7:78)
    at LOADER_EXECUTION (****/node_modules/loader-runner/lib/LoaderRunner.js:132:14)
    at runSyncOrAsync (****/node_modules/loader-runner/lib/LoaderRunner.js:133:4)
    at iterateNormalLoaders (****/node_modules/loader-runner/lib/LoaderRunner.js:250:2)
    at ****/node_modules/loader-runner/lib/LoaderRunner.js:223:4
    at ****/node_modules/webpack/lib/NormalModule.js:797:16
    at Hook.eval [as callAsync] (eval at create (****/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (****/node_modules/tapable/lib/Hook.js:18:14)
    at Object.processResource (****/node_modules/webpack/lib/NormalModule.js:792:9)
    at processResource (****/node_modules/loader-runner/lib/LoaderRunner.js:220:11)
    at iteratePitchingLoaders (****/node_modules/loader-runner/lib/LoaderRunner.js:171:10)
    at iteratePitchingLoaders (****/node_modules/loader-runner/lib/LoaderRunner.js:178:10)
    at ****/node_modules/loader-runner/lib/LoaderRunner.js:189:18
    at handleResult (****/node_modules/loader-runner/lib/loadLoader.js:53:2)
    at loadLoader (****/node_modules/loader-runner/lib/loadLoader.js:35:10)
    at iteratePitchingLoaders (****/node_modules/loader-runner/lib/LoaderRunner.js:182:2)

```

**Comment by antfu** [comment]
Try v0.2.0

**Comment by sxzz** [comment]
Thanks!
