### ISSUE TITLE
Parsed failed

### ISSUE THREAD

**Issue by sxzz** [antfu/vue2-script-setup-transform#9]
https://github.com/antfu/vue2-script-setup-transform/blob/03b03cf5c603441c5980cea1c9a442616a635abd/playground/App.vue#L1-L5

```diff
<template>
- <div>
+ <div :style="{ 'text-align': 'right' }">
    <hello-world name="Vue 2" @update="onUpdate" />
  </div>
</template>

<script setup lang="ts">
import HelloWorld from './HelloWorld.vue'

function onUpdate(e: any) {
  console.log(e)
}
</script>
```

Error:
```
● transform › App.vue

    SyntaxError: Missing semicolon. (1:14)

      at Parser._raise (node_modules/.pnpm/@babel+parser@7.15.3/node_modules/@babel/parser/src/parser/error.js:134:45)
      at Parser.raiseWithData (node_modules/.pnpm/@babel+parser@7.15.3/node_modules/@babel/parser/src/parser/error.js:129:17)
      at Parser.raise (node_modules/.pnpm/@babel+parser@7.15.3/node_modules/@babel/parser/src/parser/error.js:78:17)
      at Parser.semicolon (node_modules/.pnpm/@babel+parser@7.15.3/node_modules/@babel/parser/src/parser/util.js:137:10)
      at Parser.parseExpressionStatement (node_modules/.pnpm/@babel+parser@7.15.3/node_modules/@babel/parser/src/parser/statement.js:891:10)
      at Parser.parseStatementContent (node_modules/.pnpm/@babel+parser@7.15.3/node_modules/@babel/parser/src/parser/statement.js:375:19)
      at Parser.parseStatement (node_modules/.pnpm/@babel+parser@7.15.3/node_modules/@babel/parser/src/parser/statement.js:230:17)
      at Parser.parseBlockOrModuleBlockBody (node_modules/.pnpm/@babel+parser@7.15.3/node_modules/@babel/parser/src/parser/statement.js:966:25)
      at Parser.parseBlockBody (node_modules/.pnpm/@babel+parser@7.15.3/node_modules/@babel/parser/src/parser/statement.js:942:10)
      at Parser.parseBlock (node_modules/.pnpm/@babel+parser@7.15.3/node_modules/@babel/parser/src/parser/statement.js:912:10)

```

**Comment by sxzz** [comment]
https://github.com/antfu/vue2-script-setup-transform/blob/03b03cf5c603441c5980cea1c9a442616a635abd/src/parse.ts#L119

```diff
+ code = `(${code})`
  const ast = parse(code, options) as any
```

add a bracket maybe can solve this.

**Comment by sxzz** [comment]
...Another problem.

```diff
<template>
  <div :style="{ 'text-align': 'right' }">
    <hello-world name="Vue 2" @update="onUpdate" />
+   <span>{{ data.title }}</span>
  </div>
</template>

<script setup lang="ts">
import HelloWorld from './HelloWorld.vue'

function onUpdate(e: any) {
  console.log(e)
}

+ const data = {
+   title: 'hello',
+ }
</script>
```

Output:
```javascript
return {
  onUpdate,
  data,
  title // remove this
};
```

**Comment by sxzz** [comment]
https://github.com/antfu/vue2-script-setup-transform/commit/be5be032922eac6ceb3ee9e7e047eec6a95f06fd#r55250511

**Comment by sxzz** [comment]
And it should handle `v-for` with index


```vue
<template>
  <div v-if="show">
    <div v-for="(str, index) in arr" :key="str">
      {{ str }}{{ index }}
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      show: false,
      arr: ['Hello', 'World'],
    }
  },
}
</script>
```

**Comment by sxzz** [comment]
I'm sooorry... but 
```vue
<template>
  <div></div>
</template>

<script setup>
import { toRefs } from 'vue'
const state = { data: 'hello' }
const { data } = toRefs(state)
</script>
```
```
  ● transform › fixture › Test.vue

    TypeError: Cannot read property 'replace' of undefined

      43 |   const returns = Array.from(identifiers).filter(i => result.template.identifiers.has(i))
      44 |   const components = Array.from(identifiers).filter(i => result.template.components.has(i)
    > 45 |     || result.template.components.has(camelize(i))
         |                                       ^
      46 |     || result.template.components.has(capitalize(camelize(i))),
      47 |   )
      48 |

```
